## 라이브러리 불러오기
- 라이브러리 불러오고, 버전 확인


In [ ]:
# import numpy as np
# print(np.__version__)

import numpy
print(numpy.__version__)

1.21.6


## NumPy 배열로 변환
- 수치 연산을 하고 싶다!
- 파이썬 기초 자료형을 배열로 변환한다!
--> 형변환 이 개념과 유사

In [ ]:
temp = [1, 2, 3, 4, 5, 6, 7, 8]
result = np.array(temp)
print(type(result))
print(result)

<class 'numpy.ndarray'>
[1 2 3 4 5 6 7 8]


- 배열의 크기
- 배열은 1차원 / 2차원 / 3차원

In [ ]:
result.shape # 값이 몇개인지

(8,)

In [ ]:
result.ndim # 몇차원의 배열인지

1

- 다차원 배열 만들자

In [ ]:
temp = np.array([[2, 4 , 6], [8, 10, 12]])
print(temp)
print(temp.shape)
print(temp.ndim)

[[ 2  4  6]
 [ 8 10 12]]
(2, 3)
2


- 3차원 배열도 가능
- 4차원 가능....

## 여러 배열 생성 기본 함수
- np.arange()

In [ ]:
temp = np.arange(5)
temp

array([0, 1, 2, 3, 4])

In [ ]:
temp_z = np.zeros((2, 2, 2))
print(temp_z)
print(temp_z.shape)
print(temp_z.ndim)

# 데이터 타입
print(temp_z.dtype)

[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]
(2, 2, 2)
3
float64


- 데이터 타입 크기 지정


In [ ]:
temp_one = np.ones((3,4), dtype='int32')
print(temp_one)
print(temp_one.dtype)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
int32


In [ ]:
result = temp_one.reshape(-1, 2) # 알아서 계산
print(result)
print(result.shape)
result = temp_one.reshape(2, 2, 3) # 재배열 # 1차원, 2차원, ...  다차원도 가능
print(result)
print(result.shape)

(6, 2)
[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]
(2, 2, 3)


## 인덱싱 슬라이싱


In [ ]:
temp = np.arange(0, 4)
print(temp)

[0 1 2 3]


In [ ]:
temp[0:2] # 슬라이싱

array([0, 1])

In [ ]:
temp = np.arange(3, 30, 3).reshape(3, 3)
temp

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27]])

In [ ]:
temp[0:2, 0:3] # [행, 열]

array([[ 3,  6,  9],
       [12, 15, 18]])

In [ ]:
temp[1:3, :]

array([[12, 15, 18],
       [21, 24, 27]])

In [ ]:
temp[:, 1:3]

array([[ 6,  9],
       [15, 18],
       [24, 27]])

## 난수 생성
- 임의의 숫자 생성

In [ ]:
from numpy import random
x = random.rand()
# 같은 것
# import numpy
# x = numpy.random.rand()

print(x)

0.2777358168987767


In [ ]:
from numpy import random
x = random.rand(2,5)
print(x)

[[0.17882267 0.63951817 0.86442301 0.9657287  0.33975646]
 [0.69272102 0.01212002 0.11382888 0.19537494 0.57856842]]


- 임의의 정수


In [ ]:
from numpy import random
x = random.randint(100, size = (5, 2 ,3))
print(x)

[[[69 82 36]
  [76 81 71]]

 [[73 81 21]
  [30 89 79]]

 [[35 39 61]
  [79 61 69]]

 [[43 50 96]
  [13 54 71]]

 [[ 1  0 65]
  [29 80 72]]]


## 배열 연산

In [ ]:
array01 = random.randint(100, size = (5,2))
array02 = random.randint(1000, size = (5,2))

print(array01)
print(array02)

[[16  7]
 [29 17]
 [67 75]
 [27 24]
 [58 24]]
[[791 999]
 [664 236]
 [648 180]
 [189  95]
 [598 421]]


In [ ]:
import numpy as np

# 덧셈
np.add(array01, array02)

array([[ 807, 1006],
       [ 693,  253],
       [ 715,  255],
       [ 216,  119],
       [ 656,  445]])

In [ ]:
# 뺄셈
np.subtract(array01, array02)

array([[-775, -992],
       [-635, -219],
       [-581, -105],
       [-162,  -71],
       [-540, -397]])

In [ ]:
# 곱셈
np.multiply(array01, array02)

array([[12656,  6993],
       [19256,  4012],
       [43416, 13500],
       [ 5103,  2280],
       [34684, 10104]])

In [ ]:
# 나눗셈
np.divide(array01, array02)

array([[0.02022756, 0.00700701],
       [0.0436747 , 0.0720339 ],
       [0.10339506, 0.41666667],
       [0.14285714, 0.25263158],
       [0.09698997, 0.05700713]])

## 소숫점 제거 

In [ ]:
array01 = np.trunc([-1.23, 1.23]) # 소숫점 제거
array01

array([-1.,  1.])

In [ ]:
array01 = np.round([-1.231231312313, 1.234123123144], 3) # 셋째자리 반올림
array01

array([-1.231,  1.234])

In [ ]:
array01 = np.floor([-1.231231312313, 1.234123123144]) # 내림
array01

array([-2.,  1.])

In [ ]:
array01 = np.ceil([-1.231231312313, 1.234123123144]) # 올림
array01

array([-1.,  2.])

## NumPy 조건식
- numpy.select() : 다중조건문
- numpy.where() : 단일조건문

In [ ]:
array01 = np.arange(10)
array01 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# 배열에서 5 미만이면, 원래 값 반환, 그 외에는 원래 값 * 100
import numpy as np
#        조건식         참       거짓
np.where(array01 < 5, array01, array01 * 100)

array([  0,   1,   2,   3,   4, 500, 600, 700, 800, 900])

- 다중조건

In [ ]:
# 배열에서 3 미만이면, 원래 값 + 10, 7 이상이면 * 100, 그 외에는 원래값
cond_list =   [array01 < 3,  array01 >= 7]
result_list = [array01 + 10, array01 * 100]

# np.select(조건리스트, 결과리스트, default 값)
np.select(cond_list, result_list, default = array01)

array([ 10,  11,  12,   3,   4,   5,   6, 700, 800, 900])